apiVersion: broker.amq.io/v2alpha5
kind: ActiveMQArtemis
metadata:
  name: ex-aao
  namespace: pam-camel-demo
spec:
  acceptors:
    - expose: true
      name: amqp
      port: 5672
      protocols: AMQP
  addressSettings: {}
  console:
    expose: true
  deploymentPlan:
    size: 1
    podSecurity: {}
    resources: {}
    readinessProbe: {}
    messageMigration: false
    extraMounts: {}
    managementRBACEnabled: true
    livenessProbe: {}
    journalType: nio
    image: placeholder
    storage: {}
  upgrades:
    enabled: false
    minor: false
