apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: process-topic
  namespace: pam-camel-demo
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3

