apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: rhpam-trial
  namespace: pam-camel-demo
spec:
  environment: rhpam-trial
  objects:
    servers:
      - kafka:
          bootstrapServers: 'my-cluster-kafka-brokers:9092'
        kafkaJbpmEventEmitters:
          bootstrapServers: 'my-cluster-kafka-brokers:9092'

